kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: banzaicloud/drone-kaniko
    settings:
      registry: 127.0.0.1:5000
      repo: 127.0.0.1:5000/kaolin
  - name: test
    image: kaolin
    commands:
      - ls
      - ls /data/
      - touch /data/FOO.bar
      - ls /data/
      - rm /data/FOO.bar


# 0.8
# pipeline:
#   tests:
#     image: pytorch:1.2-cuda10.0-cudnn7-devel
#     commands:
#       - source setenv.sh
#       - python setup.py develop
#       - pytest --cov=kaolin/ tests/