kind: pipeline
type: docker
name: default

steps:
- name: test
  image: pytorch/pytorch:1.2-cuda10.0-cudnn7-devel
  commands:
  - /bin/bash -c "pip install opencv-python"
  - /bin/bash -c "source setenv.sh"
  - /bin/bash -c "python setup.py develop"
  - /bin/bash -c "pytest --cov=kaolin/ tests/"


# 0.8
# pipeline:
#   tests:
#     image: pytorch:1.2-cuda10.0-cudnn7-devel
#     commands:
#       - source setenv.sh
#       - python setup.py develop
#       - pytest --cov=kaolin/ tests/