kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker:latest
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t kaolin .

  - name: test
    image: kaolin
    commands:
      - ls
      - ls /data/
      - touch /data/FOO.bar
      - ls /data/
      - rm /data/FOO.bar


# 0.8
# pipeline:
#   tests:
#     image: pytorch:1.2-cuda10.0-cudnn7-devel
#     commands:
#       - source setenv.sh
#       - python setup.py develop
#       - pytest --cov=kaolin/ tests/