kind: pipeline
type: docker
name: default

steps:
  - name: build
    # image: docker
    # commands:
    # - docker build -t kaolin .
    image: banzaicloud/drone-kaniko
    settings:
      registry: registry.gitlab.com
      repo: nv-kaolin/kaolin-ci/kaolin
      tags: ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password
  - name: test
    image: registry.gitlab.com/nv-kaolin/kaolin-ci/kaolin:${DRONE_COMMIT_SHA}
    commands:
      - ls
      - ls /data/
      - touch /data/FOO.bar
      - ls /data/
      - rm /data/FOO.bar


# 0.8
# pipeline:
#   tests:
#     image: pytorch:1.2-cuda10.0-cudnn7-devel
#     commands:
#       - source setenv.sh
#       - python setup.py develop
#       - pytest --cov=kaolin/ tests/