kind: pipeline
type: docker
name: default

steps:
- name: test
  image: pytorch/pytorch:1.2-cuda10.0-cudnn7-devel
  commands:
  - /bin/bash -c "source setenv.sh"
  - /bin/bash -c "echo $LD_LIBRARY_PATH"
  - /bin/bash -c "source setenv.sh; echo $LD_LIBRARY_PATH"


# 0.8
# pipeline:
#   tests:
#     image: pytorch:1.2-cuda10.0-cudnn7-devel
#     commands:
#       - source setenv.sh
#       - python setup.py develop
#       - pytest --cov=kaolin/ tests/